/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER A5145433WF
 */
public class AplikasiAgendaHarian extends javax.swing.JFrame {
    DefaultTableModel model;

public class table extends javax.swing.JFrame {
    DefaultTableModel model;
    
}
    /**
     * Creates new form AplikasiAgendaHarian
     */
    public AplikasiAgendaHarian() {
        initComponents();
         Object kolom[]={"Nama", "Hari", "Tanggal", "Agenda Harian"};
        Object data[][]={{"Putra", "Senin", "25 November 2023", "Kuliah"},
                         {"Siti", "Selasa", "25 November 2023", "Belajar"}};
        
        model = new DefaultTableModel(data,kolom);
        jTable2.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        ComboBoxHari = new javax.swing.JComboBox<>();
        TFTanggal = new javax.swing.JTextField();
        RBKuliah = new javax.swing.JRadioButton();
        RBGym = new javax.swing.JRadioButton();
        RBSholat = new javax.swing.JRadioButton();
        RBBelajar = new javax.swing.JRadioButton();
        RBNongkrong = new javax.swing.JRadioButton();
        RBMainGame = new javax.swing.JRadioButton();
        buttonTambah = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AplikasiAgendaHarian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hari");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tanggal");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Agenda Harian");

        TFnama.setBackground(new java.awt.Color(0, 0, 0));
        TFnama.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        TFnama.setForeground(new java.awt.Color(255, 255, 255));

        ComboBoxHari.setBackground(new java.awt.Color(0, 0, 0));
        ComboBoxHari.setEditable(true);
        ComboBoxHari.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        ComboBoxHari.setForeground(new java.awt.Color(255, 255, 255));
        ComboBoxHari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilihan---", "Senin", "Selasa", "Rabu", "Kamis", "Jum'at", "Sabtu", "Minggu" }));

        TFTanggal.setBackground(new java.awt.Color(0, 0, 0));
        TFTanggal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        TFTanggal.setForeground(new java.awt.Color(255, 255, 255));

        RBKuliah.setBackground(new java.awt.Color(0, 0, 0));
        RBKuliah.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        RBKuliah.setForeground(new java.awt.Color(255, 255, 255));
        RBKuliah.setText("Kuliah");

        RBGym.setBackground(new java.awt.Color(0, 0, 0));
        RBGym.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        RBGym.setForeground(new java.awt.Color(255, 255, 255));
        RBGym.setText("Gym");

        RBSholat.setBackground(new java.awt.Color(0, 0, 0));
        RBSholat.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        RBSholat.setForeground(new java.awt.Color(255, 255, 255));
        RBSholat.setText("Sholat");

        RBBelajar.setBackground(new java.awt.Color(0, 0, 0));
        RBBelajar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        RBBelajar.setForeground(new java.awt.Color(255, 255, 255));
        RBBelajar.setText("Belajar");

        RBNongkrong.setBackground(new java.awt.Color(0, 0, 0));
        RBNongkrong.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        RBNongkrong.setForeground(new java.awt.Color(255, 255, 255));
        RBNongkrong.setText("Nongkrong");

        RBMainGame.setBackground(new java.awt.Color(0, 0, 0));
        RBMainGame.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        RBMainGame.setForeground(new java.awt.Color(255, 255, 255));
        RBMainGame.setText("Main Game");

        buttonTambah.setBackground(new java.awt.Color(0, 0, 0));
        buttonTambah.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        buttonTambah.setForeground(new java.awt.Color(255, 255, 255));
        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonUbah.setBackground(new java.awt.Color(0, 0, 0));
        buttonUbah.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        buttonUbah.setForeground(new java.awt.Color(255, 255, 255));
        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonHapus.setBackground(new java.awt.Color(0, 0, 0));
        buttonHapus.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 255, 255));
        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(0, 0, 0));
        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFnama)
                    .addComponent(ComboBoxHari, 0, 185, Short.MAX_VALUE)
                    .addComponent(TFTanggal))
                .addGap(99, 99, 99)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBKuliah)
                    .addComponent(RBSholat)
                    .addComponent(RBNongkrong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBMainGame)
                    .addComponent(RBBelajar)
                    .addComponent(RBGym))
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(RBKuliah)
                    .addComponent(RBGym))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboBoxHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBSholat)
                    .addComponent(RBBelajar))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBNongkrong)
                    .addComponent(RBMainGame))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambah)
                    .addComponent(buttonHapus)
                    .addComponent(buttonUbah))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        //kode menambahakan agenda
        String Nama, Hari, Tanggal, AgendaHarian;
        Nama= TFnama.getText();
        Tanggal= TFTanggal.getText();
        Hari= (String) ComboBoxHari.getSelectedItem();
        
        //Kode untuk Radio Button
         AgendaHarian ="";
        if(RBKuliah.isSelected()==true){
            AgendaHarian = "Kuliah";
        }
        if(RBGym.isSelected()==true){
            AgendaHarian = "Gym";
        }
        if(RBSholat.isSelected()==true){
            AgendaHarian = "Sholat";
        }
        if(RBNongkrong.isSelected()==true){
            AgendaHarian = "Nongkrong";
        }
        else {
            AgendaHarian = "Main Game";
        }
        
        //Kode untuk Menambahkan kedalam table
        model.addRow(new Object []{Nama, Hari, Tanggal, AgendaHarian});
        //Kode menampilkan ke table
        jTable2.setModel(model);
        
        
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // Kode untuk Menghapus 
        int selectedRow = jTable2.getSelectedRow();
    if (selectedRow != -1) {
        model.removeRow(selectedRow);
    } else {
        
    }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // Kode Untuk Mengubah data
        int selectedRow = jTable2.getSelectedRow();
    if (selectedRow != -1) {
        String Nama = TFnama.getText();
        String Tanggal = TFTanggal.getText();
        String Hari = (String) ComboBoxHari.getSelectedItem();
        String AgendaHarian = "";

        if (RBKuliah.isSelected()) {
            AgendaHarian = "Kuliah";
        } else if (RBGym.isSelected()) {
            AgendaHarian = "Gym";
        } else if (RBSholat.isSelected()) {
            AgendaHarian = "Sholat";
        } else if (RBNongkrong.isSelected()) {
            AgendaHarian = "Nongkrong";
        } else if (RBMainGame.isSelected()) {
            AgendaHarian = "Main Game";
        }

        model.setValueAt(Nama, selectedRow, 0);
        model.setValueAt(Hari, selectedRow, 1);
        model.setValueAt(Tanggal, selectedRow, 2);
        model.setValueAt(AgendaHarian, selectedRow, 3);
    } else {
        
    }
    }//GEN-LAST:event_buttonUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiAgendaHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiAgendaHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiAgendaHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiAgendaHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiAgendaHarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxHari;
    private javax.swing.JRadioButton RBBelajar;
    private javax.swing.JRadioButton RBGym;
    private javax.swing.JRadioButton RBKuliah;
    private javax.swing.JRadioButton RBMainGame;
    private javax.swing.JRadioButton RBNongkrong;
    private javax.swing.JRadioButton RBSholat;
    private javax.swing.JTextField TFTanggal;
    private javax.swing.JTextField TFnama;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
